version: '3.8'

services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb-data:/data/db
    networks:
      - bookcamp-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass123
    depends_on:
      - mongodb
    networks:
      - bookcamp-network

  bookcamp-app:
    image: app:1.0
    container_name: bookcamp-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - bookcamp-network

networks:
  bookcamp-network:

volumes:
  mongodb-data: